# Generated by Django 6.0.6 on 2026-08-23 05:21
#
# Hand-modified: CustomUser reuses the pre-existing 'auth_user' table (rather
# than creating a new 'users_customuser' table) so every foreign key already
# pointing at auth_user keeps working, and no user data has to be copied.
# The state_operations describe the model as Django/ORM sees it; the
# database_operations are idempotent so they work both on a database that
# already has 'auth_user' (adds the new columns) and on a brand new database
# (creates the table from scratch, since 'auth' skips it once swapped out).

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


CREATE_OR_UPGRADE_AUTH_USER_SQL = """
CREATE TABLE IF NOT EXISTS "auth_user" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamptz NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamptz NOT NULL,
    "email" varchar(254) NOT NULL,
    "phone_number" varchar(15) NULL,
    "is_email_verified" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "auth_user" ADD COLUMN IF NOT EXISTS "phone_number" varchar(15) NULL;
ALTER TABLE "auth_user" ADD COLUMN IF NOT EXISTS "is_email_verified" boolean NOT NULL DEFAULT false;
ALTER TABLE "auth_user" ADD COLUMN IF NOT EXISTS "created_at" timestamptz;
ALTER TABLE "auth_user" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;

UPDATE "auth_user" SET "email" = "username" || '@placeholder.local' WHERE "email" IS NULL OR "email" = '';
UPDATE "auth_user" SET "created_at" = "date_joined" WHERE "created_at" IS NULL;
UPDATE "auth_user" SET "updated_at" = "date_joined" WHERE "updated_at" IS NULL;

ALTER TABLE "auth_user" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE "auth_user" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "auth_user" ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "auth_user" ALTER COLUMN "updated_at" SET DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auth_user_username_key') THEN
        ALTER TABLE "auth_user" ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auth_user_email_key') THEN
        ALTER TABLE "auth_user" ADD CONSTRAINT "auth_user_email_key" UNIQUE ("email");
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "users_customuser_groups" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "customuser_id" bigint NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("customuser_id", "group_id")
);
CREATE INDEX IF NOT EXISTS "users_customuser_groups_customuser_id_idx" ON "users_customuser_groups" ("customuser_id");
CREATE INDEX IF NOT EXISTS "users_customuser_groups_group_id_idx" ON "users_customuser_groups" ("group_id");

CREATE TABLE IF NOT EXISTS "users_customuser_user_permissions" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "customuser_id" bigint NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("customuser_id", "permission_id")
);
CREATE INDEX IF NOT EXISTS "users_customuser_user_perm_customuser_id_idx" ON "users_customuser_user_permissions" ("customuser_id");
CREATE INDEX IF NOT EXISTS "users_customuser_user_perm_permission_id_idx" ON "users_customuser_user_permissions" ("permission_id");
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CustomUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                        ('phone_number', models.CharField(blank=True, help_text='Phone number format: +1234567890', max_length=15, null=True, verbose_name='phone number')),
                        ('is_email_verified', models.BooleanField(default=False, help_text="Designates whether this user's email has been verified.", verbose_name='email verified')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'user',
                        'verbose_name_plural': 'users',
                        'ordering': ['-created_at'],
                        'db_table': 'auth_user',
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_OR_UPGRADE_AUTH_USER_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
