# Generated by Django 6.0.6 on 2026-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionitem',
            name='expense_tra_transac_f8cfca_idx',
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
