# Generated by Django 6.0.6 on 2026-07-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_amount_positive',
        ),
    ]
