# Generated by Django 6.0.6 on 2026-10-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_repair_favorite_description_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritedescription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
