# Generated by Django 6.0.6 on 2026-10-02 22:51

import django.db.models.deletion
import expense.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_settlement_split_accounting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True, default=expense.models.notification_expiry)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='user_notifi_user_id_568eb7_idx')],
            },
        ),
    ]
