# Generated by Django 6.0.6 on 2026-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
